sudo: required
services:
    - docker

before_install:
    - docker build -t adegruiter/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true adegruiter/react-test npm test

after_success:
    - docker build -t adegruiter/multi-client ./client
    - docker build -t adegruiter/multi-nginx ./nginx
    - docker build -t adegruiter/multi-server ./server
    - docker build -t adegruiter/multi-worker ./worker
    # Log in to the Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to Docker Hub
    - docker push adegruiter/multi-client
    - docker push adegruiter/multi-nginx
    - docker push adegruiter/multi-server
    - docker push adegruiter/multi-worker

deploy:
    provider: elasticbeanstalk
    region: ap-southeast-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-ap-southeast-2-830254667090
    bucket_path: docker-multi
    edge: true
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY